### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iamabutalha**

### CODE REVIEW

**Comment by iamabutalha** [comment]
Updated

**Comment by SS240101962** [comment]
Who are you ask me

**Comment by iamabutalha** [comment]
lamo doing this for a GitHub contributer badge 😣

**Comment by SS240101962** [comment]
As Salam Alaikum

Please find below the timings and links for today's Math and CS sessions.
Every Monday, Wednesday and Saturday we will follow this timetable for Math
& CS sessions.

Computer Class
 Timings: (4 pm - 4:50 pm)

meet.google.com/vrh-kdij-xfz

Math Class
Timings (5 pm - 5:50 pm)

meet.google.com/ydr-wsrz-kro

Please make sure to use only the account provided by Virtual STEM School to
join the session otherwise, you will not be able to join.
Happy learning!

**Comment by iamabutalha** [comment]
Where do I find a virtual stem school account?

**Comment by iamabutalha** [comment]
When ever I try to join these links, they either they are not giving me access or sometime the meeting do not exist .

**Comment by iamabutalha** [comment]
As Salam Alaikum hope you are doing well, We have created a website that is currently in development mode,  So we are trying to get more user to that website for suggestions and testing purpose, feel free to contribute if you find any issue in our site or if the UI is not interactive.
 we will appreciate your time Thank You
https://iamabutalha.github.io/webapp/

**Pull request closed without merging**
